sudo: required

services:
  - docker

install: true

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build . -t ctheory/alpine-nginx:latest
  - docker push ctheory/alpine-nginx:latest
